model:
  numSlots: 6
  numPoles: 2
  iForcePeak: 4.2
  iFluxPeak: 0
  wasteFactor: 0.1

coil:
  radius: 5
  height: 6
  spacing: 0.7
  material: 0.315
  magneticGap: 1
  
pole:
  radius: 6
  height: 20
  material: N42
