[[material]]
name = "Air"
tag = "environmental"

[material.physical]
lamination = "solid"
lamination_fill = 1.0
lamination_thickness = 1
wire_diameter = 0

[material.magnetic]
relative_permeability = [1.0, 1.0]
coercivity = 0
Remanence = 0
current_density = 0

[material.electrical]
relative_permittivity = [1.0006, 1.0006]
conductivity = 5e-15
volume_charge_density = 0

[material.thermal]
conductivity = [0.0181, 0.0181]
volumetric_heat_source = 0
temp_dependence = [
  [200.0, 0.0181],
  [250.0, 0.0223],
  [300.0, 0.0261],
  [350.0, 0.0297],
  [400.0, 0.0331],
  [450.0, 0.0363],
  [500.0, 0.0395],
  [550.0, 0.0426],
  [600.0, 0.0456],
  [700.0, 0.0513],
  [800.0, 0.0569],
  [900.0, 0.0625],
  [1000.0, 0.0672],
  [1200.0, 0.0759],
  [1400.0, 0.0835],
  [1600.0, 0.0904],
  [1800.0, 0.097],
  [2000.0, 0.1032]
]

[[material]]
name = "Pure Iron"
type = ""

[material.physical]
lamination = "solid"
lamination_fill = 1.0
lamination_thickness = 1
wire_diameter = 0

[material.magnetic]
relative_permeability = [14872, 14872]
coercivity = 0
Remanence = 0
current_density = 0

[material.electrical]
relative_permittivity = [0, 0]
conductivity = 1.044e6
volume_charge_density = 0

[material.thermal]
conductivity = [83, 83]
volumetric_heat_source = 0
temp_dependence = [
  [273.0, 83.0],
  [473.0, 66.0],
  [673.0, 53.0],
  [873.0, 41.0],
  [1073.0, 32.0],
  [1273.0, 30.0]
]


[[material]]
name = "copper wire"
tag = "wire"

[material.physical]
lamination = "solid"
lamination_fill = 1.0
lamination_thickness = 1
wire_diameter = 0

[material.magnetic]
relative_permeability = [1.0, 1.0]
coercivity = 0
Remanence = 0
current_density = 0

[material.electrical]
relative_permittivity = [0, 0]
conductivity = 5.8e7
volume_charge_density = 0

[material.thermal]
conductivity = [401, 401]
volumetric_heat_source = 0
temp_dependence = [
  [273.0, 401.0],
  [473.0, 389.0],
  [673.0, 378.0],
  [873.0, 366.0],
  [1073.0, 352.0],
  [1273.0, 336.0]
]


[[material]]
name = "NdFeB"
tag = "magnet"

[material.physical]
lamination = "solid"
lamination_fill = 1.0
lamination_thickness = 1
wire_diameter = 0

[material.magnetic]
relative_permeability = [1.05, 1.05]
coercivity = 836420
Remanence = 1.104
current_density = 0

[material.electrical]
relative_permittivity = [0, 0]
conductivity = 0.667e6
volume_charge_density = 0


[material.thermal]
conductivity = [16.5, 16.5]
volumetric_heat_source = 0
temp_dependence = [
  [273.0, 3.36],
  [323.0, 3.64],
  [373.0, 3.91],
  [423.0, 4.17],
  [473.0, 4.42]
]

[material.grades]
N30 = { coercivity = 836420, Remanence = 1.104 }
N33 = { coercivity = 878619, Remanence = 1.104 }
N35 = { coercivity = 905659, Remanence = 1.104 }
N38 = { coercivity = 944771, Remanence = 1.104 }
N40 = { coercivity = 969969, Remanence = 1.104 }
N42 = { coercivity = 994529, Remanence = 1.104 }
N45 = { coercivity = 1030272, Remanence = 1.104 }
N48 = { coercivity = 1014538, Remanence = 1.104 }
N50 = { coercivity = 987837, Remanence = 1.104 }
N52 = { coercivity = 956180, Remanence = 1.104 }
N55 = { coercivity = 922850, Remanence = 1.104 }
